name: Build Light Transparent Picons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git binutils pngquant imagemagick librsvg2-bin jq xz-utils

      - name: Build servicelist and picons
        run: |
          chmod +x 1-build-servicelist.sh 2-build-picons.sh
          
          # بناء القائمة والبيكونات بناءً على الملفات والمقاس المحدد في backgrounds.conf
          ./1-build-servicelist.sh srp --name=mybox
          ./2-build-picons.sh srp --name=mybox

      - name: Release Picons
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Picons 220x132 Light Transparent"
          files: build-output/binaries-*/*.tar.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
